#!/usr/bin/env bash
PROTOCOL="http://"
HOST="blackbox.relaxpc.com:5005/"
PLAYER="Carpet%20Bar"

########################################
# END CUSTOMIZATION
########################################

BASE=$PROTOCOL$HOST$PLAYER
echo "Base: $BASE"
command="$BASE/say/Ready%20to%20serve%20you/en/60"
echo "Doing: $command"
curl $command

while true;
do
  read -n 1 c
  echo "You said |$c|"
  case "$c" in
    [S]|" ")
      echo "Space!"
      command="$BASE/playpause"
      echo "Doing: $command"
      curl $command
      ;;
    [aA]*)
      echo
      command="$BASE/play/favorites/America"
      echo "Doing: $command"
      curl $command
      ;;
    [pP]*)
      echo
      command="$BASE/play"
      echo "Doing: $command"
      curl $command
      ;;
    [nN]|">"*)
      echo
      command="$BASE/next"
      echo "Doing: $command"
      curl $command
      ;;
    [*]|">"*)
      echo
      command="$BASE/state"
      echo "Doing: $command"
      curl $command
      ;;
    "<"*)
      echo
      command="$BASE/previous"
      echo "Doing: $command"
      curl $command
      ;;
    ","*)
      echo
      command="$BASE/timeseek/0"
      echo "Doing: $command"
      curl $command
      ;;
    [kK]*) # kunr
      echo
      command="$BASE/tunein/play/35921"
      echo "Doing: $command"
      curl $command
      ;;
    [q]*) # kqed
      echo
      command="$BASE/tunein/play/34804"
      echo "Doing: $command"
      curl $command
      ;;
    [b]*) # kcrw
      echo
      command="$BASE/tunein/play/44525"
      echo "Doing: $command"
      curl $command
      ;;
    [B]*) # back some seconds
      REWIND=30
      echo Going BACK!
      ELAPSED=`curl -s http://blackbox.relaxpc.com:5005/Carpet%20Bar/state|sed -e 's/.*\"elapsedTime\":\([0-9]*\).*/\1/'`
      echo ELAPSED: $ELAPSED
      if [ "$ELAPSED" -gt "$REWIND" ]
      then
	  BACK=$(($ELAPSED-$REWIND))
      else
	BACK=0
      fi
      command="$BASE/timeseek/$BACK"
      echo "Doing: $command"
      curl $command
      ;;
    [l]*)
      echo
      command="$BASE/musicsearch/library/album/blues+five+spot"
      echo "Doing: $command"
      curl $command
      ;;
    [y]*) # wnyc
      echo
      command="$BASE/tunein/play/21606"
      echo "Doing: $command"
      curl $command
      ;;
    [s]*) # stories
      echo
      command="$BASE/favorite/Stories"
      echo "Doing: $command"
      curl $command
      ;;
    [0-9]*)
      command="$BASE/volume/${c}0"
      echo "Got $c. Doing: $command"
      curl $command
      ;;
    [+-]*)
      command="$BASE/volume/${c}1"
      echo "Got $c. Doing: $command"
      curl $command
      ;;
    [t]*)
      time=`date +%R`
      # command="$BASE/pauseall"
      # echo "Got $c. Doing: $command"
      # curl $command
      command="$BASE/say/The%20time%20is%20$time/en/60"
      echo "Doing: $command"
      curl $command
      # command="$BASE/resumeall"
      # echo "Doing: $command"
      # curl $command
      ;;
    [?]*)
      command="$BASE/sleep/60"
      echo "Got $c. Doing: $command"
      curl $command
      ;;
    "Q"*)
      echo "Done."
      exit
  esac
  command="$BASE/say/sonos-script-exiting/en/60"
  echo "Doing: $command"
  curl $command
done
